version: "3.3"
services:
    frontend:
        image: frontend
        container_name: frontend
        ports: 
            - 2080:80
        build:
            context: ./frontend
    
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672

    db:
        image: postgres:11
        container_name: postgres
        ports:
            - 5433:5432
        environment:
            POSTGRES_PASSWORD: salespassword
            POSTGRES_USER: salesservice
            PGDATA : /var/lib/postgresql/data
        volumes:
            - data:/var/lib/postgresql/data

    ps-parser:
        image: ps-parser
        container_name: ps-parser
        depends_on: 
            - rabbitmq
        build: 
            context: ./backend/Parsers/
            dockerfile: ./PSStoreParser/Dockerfile
        env_file: 
            - ./env/PSStoreParser.env

    steam-parser:
        image: steam-parser
        container_name: steam-parser
        depends_on: 
            - rabbitmq
        build: 
            context: ./backend/Parsers/
            dockerfile: ./SteamParser/Dockerfile
        env_file: 
            - ./env/SteamParser.env

    uplay-parser:
        image: uplay-parser
        container_name: uplay-parser
        depends_on: 
            - rabbitmq
        build: 
            context: ./backend/Parsers/
            dockerfile: ./UplayParser/Dockerfile
        env_file: 
            - ./env/UplayParser.env

    nintendo-parser:
        image: nintendo-parser
        container_name: nintendo-parser
        depends_on: 
            - rabbitmq
        build: 
            context: ./backend/Parsers/
            dockerfile: ./NintendoParser/Dockerfile
        env_file: 
            - ./env/NintendoParser.env

    epic-parser:
        image: epic-parser
        container_name: epic-parser
        depends_on: 
            - rabbitmq
        build: 
            context: ./backend/Parsers/EpicGamesParser

    gateway-api:
        image: gateway-api
        container_name: gateway-api
        ports:
            - 5080:80
        depends_on: 
            - db
        build: 
            context: ./backend/GameSalesApi/
            dockerfile: ./GameSalesApi/Dockerfile
        env_file: 
            - ./env/GatewayApi.env

    games-saver:
        image: games-saver
        container_name: games-saver
        depends_on: 
            - db
            - rabbitmq
        build: 
            context: ./backend/GamesServices/
            dockerfile: ./GamesSaver/Dockerfile
        env_file: 
            - ./env/GamesSaver.env
        restart: on-failure

    games-provider:
        image: games-provider
        container_name: games-provider
        ports: 
            - 6080:80
        depends_on: 
            - db
        build: 
            context: ./backend/GamesServices/
            dockerfile: ./GamesProvider/Dockerfile
        env_file: 
            - ./env/GamesProvider.env
    
volumes: 
    data: 
        driver: local
