bot:
  token: ""
  start-sticker-id: "CAACAgEAAxkBAAJcaV6ua19b1jv3Vrl4qrTnw6UkR-mWAAJ_CAAC2D_nCYiBLKfY3wW3GQQ"
  admin-id:

gateway-api: ""

game_store:
  ps: "https://store.playstation.com/ru-ua/home/games"
  nintendo: "https://www.nintendo.com/"
  steam: "https://store.steampowered.com/"
  epic: "https://www.epicgames.com/store/en-US/"
  uplay: "https://uplay.ubisoft.com/en-GB"
