name: .NET Core

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        dotnet restore ./backend/GameSalesApi/
        dotnet restore ./backend/GamesServices/
        dotnet restore ./backend/Parsers/
    - name: Build
      run: |
        dotnet build -c Release --no-restore ./backend/GameSalesApi/
        dotnet build -c Release --no-restore ./backend/GamesServices/
        dotnet build -c Release --no-restore ./backend/Parsers/
    - name: Test
      run: dotnet test --no-restore -v q ./backend/GameSalesApi/
