name: .NET Core

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Build GameSalesApi
      run: |
        dotnet restore ./backend/GameSalesApi/
        dotnet build -c Release --no-restore ./backend/GameSalesApi/
    - name: Test GameSalesApi
      run: |
        dotnet test --no-restore -v m ./backend/GameSalesApi/ApplicationBlocksTest/
        dotnet test --no-restore -v m ./backend/GameSalesApi/Infrastructure.Tests/
        dotnet test --no-restore -v m ./backend/GameSalesApi/GameSalesApiTests/
    
    - name: Build GamesServices
      run: |
        dotnet restore ./backend/GamesServices/
        dotnet build -c Release --no-restore ./backend/GamesServices/
    - name: Test GamesServices
      run: |
        dotnet test --no-restore -v m ./backend/GamesServices/GamesServicesTests/
        dotnet test --no-restore -v m ./backend/GamesServices/GamesServicesIntegrationTests/
